"""empty message

Revision ID: e29e7409b29d
Revises: 080e77d163fa
Create Date: 2020-11-08 12:40:48.714399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e29e7409b29d'
down_revision = '080e77d163fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'Show_venue_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(u'Show_venue_id_fkey', 'Show', 'Venue', ['venue_id'], ['id'],ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'Show_venue_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(u'Show_venue_id_fkey', 'Show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
